# Generated by Django 4.1.7 on 2023-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_web', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('ability', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='me')),
            ],
        ),
    ]
