# Generated by Django 4.1.7 on 2023-04-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_detail',
            field=models.TextField(default='hiii'),
        ),
    ]
