# Generated by Django 4.1.7 on 2023-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0003_library_library_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('explanation_title', models.CharField(max_length=50, null=True)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='library',
            name='library_detail',
            field=models.TextField(),
        ),
    ]
