# Generated by Django 4.1.7 on 2023-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0004_experience_alter_library_library_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('explanation_title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
            ],
        ),
    ]
