# Generated by Django 4.1.7 on 2023-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='site_link',
            field=models.CharField(default='', max_length=302),
            preserve_default=False,
        ),
    ]
