# Generated by Django 4.1.7 on 2023-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0006_education_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='site_link',
            field=models.CharField(max_length=30),
        ),
    ]
